#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ACE.Resource", IsApplication=true)]

namespace ACE
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int Blue = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int CBSA_Blue = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int AvisBttn = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int CanadaFooter = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int EnglishBttn = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int FrenchBttn = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int PrivacyBttn = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ScanButton = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int SearchButton = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int settings = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int splash_background = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Splashscreen = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080009
			public const int MakeBttn = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int ModelBttn = 2131230730;
			
			// aapt resource value: 0x7f080007
			public const int ScanBttn = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int SearchBttn = 2131230726;
			
			// aapt resource value: 0x7f08000b
			public const int YearBttn = 2131230731;
			
			// aapt resource value: 0x7f080003
			public const int avisBttn = 2131230723;
			
			// aapt resource value: 0x7f080008
			public const int contentEN = 2131230728;
			
			// aapt resource value: 0x7f080000
			public const int englishBttn = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int frenchBttn = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int imageView1 = 2131230724;
			
			// aapt resource value: 0x7f080001
			public const int privacyBttn = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int title = 2131230725;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Language = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Main = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int PrivacyPolicyEN = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int PrivacyPolicyFR = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Search = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060006
			public const int Accept = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int Avis = 2131099653;
			
			// aapt resource value: 0x7f060010
			public const int CarOnboarding = 2131099664;
			
			// aapt resource value: 0x7f060007
			public const int Decline = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int English = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int French = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int GetStarted = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int Make = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int Model = 2131099660;
			
			// aapt resource value: 0x7f060004
			public const int PrivacyBttn = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int PrivacyPolicy = 2131099649;
			
			// aapt resource value: 0x7f06000e
			public const int PrivacyPolicyContent = 2131099662;
			
			// aapt resource value: 0x7f060009
			public const int Scan = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int Search = 2131099658;
			
			// aapt resource value: 0x7f06000f
			public const int SearchOnboarding = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int Year = 2131099661;
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int MyTheme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
