#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ACE.Resource", IsApplication=true)]

namespace ACE
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int Blue = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int CBSA_Blue = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int ScanBttn = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int SearchBttn = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int englishBttn = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int frenchBttn = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int title = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Language = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050004
			public const int Accept = 2131034116;
			
			// aapt resource value: 0x7f05000b
			public const int CarOnboarding = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int Decline = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int English = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int French = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int GetStarted = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int PrivacyPolicy = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int PrivacyPolicyContent = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int Scan = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int Search = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int SearchOnboarding = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
